name: flutter_app
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/ic_add.png
    - images/ic_app_title.png
    - images/ic_delete.png
    - images/ic_dress_item_left.png
    - images/ic_home_tab_all.png
    - images/ic_home_tab_drawer.png
    - images/ic_home_tab_dress.png
    - images/ic_home_tab_personal.png
    - images/ic_more.png
    - images/ic_full_screen.png
    - images/ic_bookmark.png
    - images/img_1.png
    - images/img_2.png
    - images/img_3.png
    - images/img_4.png
    - images/img_5.png
